# Generated by Django 3.0 on 2020-08-29 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 11, 26, 28, 442062, tzinfo=utc), verbose_name='актульность ключа'),
        ),
    ]
