# Generated by Django 3.0 on 2020-08-29 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200829_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 11, 46, 10, 488647, tzinfo=utc), verbose_name='актульность ключа'),
        ),
    ]
