# Generated by Django 3.0 on 2020-09-06 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200829_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 17, 25, 4, 377778, tzinfo=utc), verbose_name='актульность ключа'),
        ),
    ]
